-- ============================================
-- AGI Index - Complete Database Schema
-- ============================================
-- This file creates the complete database from scratch.
-- Run this once on a fresh Supabase project.
-- ============================================

-- ============================================
-- 1. ENUM 타입 정의
-- ============================================
CREATE TYPE agi_category AS ENUM ('linguistic', 'multimodal');
CREATE TYPE unsuitable_reason AS ENUM ('too_broad', 'too_narrow', 'duplicate', 'other');
CREATE TYPE question_status AS ENUM ('pending', 'approved', 'rejected');

-- ============================================
-- 2. Profiles 테이블 (유저 정보)
-- ============================================
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  nickname TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 3. Questions 테이블 (AGI 후보 질문)
-- ============================================
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  category agi_category NOT NULL,
  status question_status DEFAULT 'pending',

  -- 통계 데이터 (트리거로 자동 계산)
  vote_count INT DEFAULT 0,
  suitable_count INT DEFAULT 0,
  unsuitable_count INT DEFAULT 0,
  achieved_count INT DEFAULT 0,
  not_achieved_count INT DEFAULT 0,
  current_weight FLOAT DEFAULT 0,

  -- 핵심 상태값
  is_indexed BOOLEAN DEFAULT FALSE,
  is_achieved BOOLEAN DEFAULT FALSE,
  dominant_unsuitable_reason unsuitable_reason,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 4. Votes 테이블 (투표)
-- ============================================
-- 적합도와 달성도를 독립적으로 투표 가능 (NULL 허용)
CREATE TABLE votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,

  is_suitable BOOLEAN,
  unsuitable_reason unsuitable_reason,
  is_achieved BOOLEAN,
  weight INT CHECK (weight IN (1, 2, 3)),

  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(user_id, question_id)
);

-- ============================================
-- 5. Question Translations 테이블 (다국어 번역)
-- ============================================
CREATE TABLE question_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
  lang_code VARCHAR(5) NOT NULL,
  content TEXT NOT NULL,
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(question_id, lang_code)
);

CREATE INDEX idx_translations_question_id ON question_translations(question_id);
CREATE INDEX idx_translations_lang_code ON question_translations(lang_code);

-- ============================================
-- 6. Daily Metrics 테이블 (매일 스냅샷)
-- ============================================
CREATE TABLE daily_metrics (
  date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
  overall_rate NUMERIC(5,2),
  linguistic_rate NUMERIC(5,2),
  multimodal_rate NUMERIC(5,2),
  linguistic_count INTEGER,
  multimodal_count INTEGER,
  total_votes INTEGER,
  total_users INTEGER,
  index_question_count INTEGER,
  candidate_question_count INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 7. AGI Stats 테이블 (실시간 통계 캐시)
-- ============================================
CREATE TABLE agi_stats (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  overall_rate NUMERIC(5,2) DEFAULT 0,
  linguistic_rate NUMERIC(5,2) DEFAULT 0,
  multimodal_rate NUMERIC(5,2) DEFAULT 0,
  linguistic_count INTEGER DEFAULT 0,
  multimodal_count INTEGER DEFAULT 0,
  total_votes INTEGER DEFAULT 0,
  total_users INTEGER DEFAULT 0,
  index_question_count INTEGER DEFAULT 0,
  candidate_question_count INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 8. Row Level Security (RLS) 설정
-- ============================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE agi_stats ENABLE ROW LEVEL SECURITY;

-- 8-1. Profiles 정책
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING ((SELECT auth.uid()) = id);

-- 8-2. Questions 정책 (승인 시스템 반영)
CREATE POLICY "Questions read policy" ON questions FOR SELECT
  USING (
    status = 'approved'
    OR (SELECT auth.uid()) = author_id
    OR (SELECT is_admin FROM profiles WHERE id = (SELECT auth.uid())) = true
  );
CREATE POLICY "Admin update" ON questions FOR UPDATE
  USING ((SELECT is_admin FROM profiles WHERE id = (SELECT auth.uid())) = true);
CREATE POLICY "Admin delete" ON questions FOR DELETE
  USING ((SELECT is_admin FROM profiles WHERE id = (SELECT auth.uid())) = true);
CREATE POLICY "Authenticated users can insert questions" ON questions FOR INSERT
  WITH CHECK ((SELECT auth.role()) = 'authenticated');

-- 8-3. Votes 정책
CREATE POLICY "Votes are viewable by everyone" ON votes FOR SELECT USING (true);
CREATE POLICY "Authenticated users can vote" ON votes FOR INSERT WITH CHECK ((SELECT auth.role()) = 'authenticated');
CREATE POLICY "Users can update own vote" ON votes FOR UPDATE USING ((SELECT auth.uid()) = user_id);

-- 8-4. Question Translations 정책
CREATE POLICY "Translations are viewable by everyone" ON question_translations FOR SELECT USING (true);
CREATE POLICY "Only admins can insert translations" ON question_translations FOR INSERT
  WITH CHECK ((SELECT is_admin FROM profiles WHERE id = (SELECT auth.uid())) = true);
CREATE POLICY "Only admins can update translations" ON question_translations FOR UPDATE
  USING ((SELECT is_admin FROM profiles WHERE id = (SELECT auth.uid())) = true);
CREATE POLICY "Only admins can delete translations" ON question_translations FOR DELETE
  USING ((SELECT is_admin FROM profiles WHERE id = (SELECT auth.uid())) = true);

-- 8-5. AGI Stats 정책
CREATE POLICY "AGI stats are viewable by everyone" ON agi_stats FOR SELECT USING (true);

-- 8-6. Daily Metrics 정책
ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Daily metrics are viewable by everyone" ON daily_metrics FOR SELECT USING (true);

-- ============================================
-- 9. 자동화 함수 & 트리거
-- ============================================

-- 9-1. 회원가입 시 Profile 자동 생성
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 9-2. 투표 시 질문 통계 자동 계산
CREATE OR REPLACE FUNCTION update_question_stats()
RETURNS TRIGGER AS $$
DECLARE
  _question_id BIGINT;
  _total INT;
  _suitable INT;
  _unsuitable INT;
  _achieved INT;
  _not_achieved INT;
  _weight_sum INT;
  _top_reason unsuitable_reason;
  _suitability_rate FLOAT;
  _achievement_rate FLOAT;
BEGIN
  IF (TG_OP = 'DELETE') THEN
    _question_id := OLD.question_id;
  ELSE
    _question_id := NEW.question_id;
  END IF;

  SELECT
    COUNT(*),
    COUNT(*) FILTER (WHERE is_suitable = true),
    COUNT(*) FILTER (WHERE is_suitable = false),
    COUNT(*) FILTER (WHERE is_achieved = true),
    COUNT(*) FILTER (WHERE is_achieved = false),
    COALESCE(SUM(weight) FILTER (WHERE is_suitable = true), 0)
  INTO _total, _suitable, _unsuitable, _achieved, _not_achieved, _weight_sum
  FROM votes
  WHERE question_id = _question_id;

  SELECT unsuitable_reason
  INTO _top_reason
  FROM votes
  WHERE question_id = _question_id AND is_suitable = false
  GROUP BY unsuitable_reason
  ORDER BY COUNT(*) DESC
  LIMIT 1;

  IF (_suitable + _unsuitable) > 0 THEN
    _suitability_rate := _suitable::float / (_suitable + _unsuitable)::float;
  ELSE
    _suitability_rate := 0;
  END IF;

  IF (_achieved + _not_achieved) > 0 THEN
    _achievement_rate := _achieved::float / (_achieved + _not_achieved)::float;
  ELSE
    _achievement_rate := 0;
  END IF;

  UPDATE questions
  SET
    vote_count = _total,
    suitable_count = _suitable,
    unsuitable_count = _unsuitable,
    achieved_count = _achieved,
    not_achieved_count = _not_achieved,
    current_weight = CASE WHEN _suitable > 0 THEN ROUND(_weight_sum::numeric / _suitable::numeric, 2) ELSE 0 END,
    dominant_unsuitable_reason = _top_reason,
    is_indexed = CASE
      WHEN _suitable >= 10 AND _suitability_rate >= 0.5 THEN TRUE
      ELSE FALSE
    END,
    is_achieved = CASE
      WHEN (_achieved + _not_achieved) > 0 AND _achievement_rate >= 0.5 THEN TRUE
      ELSE FALSE
    END
  WHERE id = _question_id;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_vote_change
  AFTER INSERT OR UPDATE OR DELETE ON votes
  FOR EACH ROW EXECUTE PROCEDURE update_question_stats();

-- 9-3. AGI Stats 자동 재계산
CREATE OR REPLACE FUNCTION recalculate_agi_stats()
RETURNS TRIGGER AS $$
DECLARE
  v_linguistic_rate NUMERIC(5,2);
  v_multimodal_rate NUMERIC(5,2);
  v_overall_rate NUMERIC(5,2);
  v_linguistic_count INTEGER;
  v_multimodal_count INTEGER;
  v_total_votes INTEGER;
  v_total_users INTEGER;
  v_index_question_count INTEGER;
  v_candidate_question_count INTEGER;
BEGIN
  -- Rate calculations (unchanged)
  SELECT
    COALESCE(AVG(CASE WHEN vote_count > 0 THEN (achieved_count::NUMERIC / vote_count) * 100 ELSE 0 END), 0),
    COUNT(*)
  INTO v_linguistic_rate, v_linguistic_count
  FROM questions
  WHERE is_indexed = true AND category = 'linguistic';

  SELECT
    COALESCE(AVG(CASE WHEN vote_count > 0 THEN (achieved_count::NUMERIC / vote_count) * 100 ELSE 0 END), 0),
    COUNT(*)
  INTO v_multimodal_rate, v_multimodal_count
  FROM questions
  WHERE is_indexed = true AND category = 'multimodal';

  IF (v_linguistic_count + v_multimodal_count) > 0 THEN
    v_overall_rate := (
      (v_linguistic_rate * v_linguistic_count) + (v_multimodal_rate * v_multimodal_count)
    ) / (v_linguistic_count + v_multimodal_count);
  ELSE
    v_overall_rate := 0;
  END IF;

  -- New Metrics Calculations
  SELECT COALESCE(SUM(vote_count), 0)
  INTO v_total_votes
  FROM questions; -- Total votes across ALL questions (or just indexed? User said "Total votes", usually implies all)
  
  -- Let's stick to total votes in the system for "Community Stats"
  SELECT COUNT(DISTINCT user_id) INTO v_total_users FROM votes;
  
  SELECT COUNT(*) INTO v_index_question_count FROM questions WHERE is_indexed = true AND status = 'approved';
  SELECT COUNT(*) INTO v_candidate_question_count FROM questions WHERE is_indexed = false AND status = 'approved';

  INSERT INTO agi_stats (
    id, overall_rate, linguistic_rate, multimodal_rate, 
    linguistic_count, multimodal_count, total_votes, 
    total_users, index_question_count, candidate_question_count, updated_at
  )
  VALUES (
    1, v_overall_rate, v_linguistic_rate, v_multimodal_rate, 
    v_linguistic_count, v_multimodal_count, v_total_votes, 
    v_total_users, v_index_question_count, v_candidate_question_count, NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    overall_rate = EXCLUDED.overall_rate,
    linguistic_rate = EXCLUDED.linguistic_rate,
    multimodal_rate = EXCLUDED.multimodal_rate,
    linguistic_count = EXCLUDED.linguistic_count,
    multimodal_count = EXCLUDED.multimodal_count,
    total_votes = EXCLUDED.total_votes,
    total_users = EXCLUDED.total_users,
    index_question_count = EXCLUDED.index_question_count,
    candidate_question_count = EXCLUDED.candidate_question_count,
    updated_at = EXCLUDED.updated_at;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Callable version
CREATE OR REPLACE FUNCTION do_recalculate_agi_stats()
RETURNS VOID AS $$
DECLARE
  v_linguistic_rate NUMERIC(5,2);
  v_multimodal_rate NUMERIC(5,2);
  v_overall_rate NUMERIC(5,2);
  v_linguistic_count INTEGER;
  v_multimodal_count INTEGER;
  v_total_votes INTEGER;
  v_total_users INTEGER;
  v_index_question_count INTEGER;
  v_candidate_question_count INTEGER;
BEGIN
  SELECT
    COALESCE(AVG(CASE WHEN vote_count > 0 THEN (achieved_count::NUMERIC / vote_count) * 100 ELSE 0 END), 0),
    COUNT(*)
  INTO v_linguistic_rate, v_linguistic_count
  FROM questions
  WHERE is_indexed = true AND category = 'linguistic';

  SELECT
    COALESCE(AVG(CASE WHEN vote_count > 0 THEN (achieved_count::NUMERIC / vote_count) * 100 ELSE 0 END), 0),
    COUNT(*)
  INTO v_multimodal_rate, v_multimodal_count
  FROM questions
  WHERE is_indexed = true AND category = 'multimodal';

  IF (v_linguistic_count + v_multimodal_count) > 0 THEN
    v_overall_rate := (
      (v_linguistic_rate * v_linguistic_count) + (v_multimodal_rate * v_multimodal_count)
    ) / (v_linguistic_count + v_multimodal_count);
  ELSE
    v_overall_rate := 0;
  END IF;

  SELECT COALESCE(SUM(vote_count), 0) INTO v_total_votes FROM questions;
  SELECT COUNT(DISTINCT user_id) INTO v_total_users FROM votes;
  SELECT COUNT(*) INTO v_index_question_count FROM questions WHERE is_indexed = true AND status = 'approved';
  SELECT COUNT(*) INTO v_candidate_question_count FROM questions WHERE is_indexed = false AND status = 'approved';

  INSERT INTO agi_stats (
    id, overall_rate, linguistic_rate, multimodal_rate, 
    linguistic_count, multimodal_count, total_votes, 
    total_users, index_question_count, candidate_question_count, updated_at
  )
  VALUES (
    1, v_overall_rate, v_linguistic_rate, v_multimodal_rate, 
    v_linguistic_count, v_multimodal_count, v_total_votes, 
    v_total_users, v_index_question_count, v_candidate_question_count, NOW()
  )
  ON CONFLICT (id) DO UPDATE SET
    overall_rate = EXCLUDED.overall_rate,
    linguistic_rate = EXCLUDED.linguistic_rate,
    multimodal_rate = EXCLUDED.multimodal_rate,
    linguistic_count = EXCLUDED.linguistic_count,
    multimodal_count = EXCLUDED.multimodal_count,
    total_votes = EXCLUDED.total_votes,
    total_users = EXCLUDED.total_users,
    index_question_count = EXCLUDED.index_question_count,
    candidate_question_count = EXCLUDED.candidate_question_count,
    updated_at = EXCLUDED.updated_at;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- AGI Stats 트리거
CREATE TRIGGER trigger_recalculate_agi_stats_on_vote
  AFTER INSERT OR UPDATE OR DELETE ON votes
  FOR EACH STATEMENT
  EXECUTE FUNCTION recalculate_agi_stats();

CREATE TRIGGER trigger_recalculate_agi_stats_on_question
  AFTER INSERT OR UPDATE OF is_indexed, category, vote_count, achieved_count OR DELETE ON questions
  FOR EACH STATEMENT
  EXECUTE FUNCTION recalculate_agi_stats();

-- 9-4. Daily Metrics 동기화 (AGI Stats 변경 시)
CREATE OR REPLACE FUNCTION sync_daily_metrics()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO daily_metrics (
    date,
    overall_rate,
    linguistic_rate,
    multimodal_rate,
    linguistic_count,
    multimodal_count,
    total_votes,
    total_users,
    index_question_count,
    candidate_question_count,
    updated_at
  )
  VALUES (
    CURRENT_DATE,
    NEW.overall_rate,
    NEW.linguistic_rate,
    NEW.multimodal_rate,
    NEW.linguistic_count,
    NEW.multimodal_count,
    NEW.total_votes,
    NEW.total_users,
    NEW.index_question_count,
    NEW.candidate_question_count,
    NOW()
  )
  ON CONFLICT (date) DO UPDATE SET
    overall_rate = EXCLUDED.overall_rate,
    linguistic_rate = EXCLUDED.linguistic_rate,
    multimodal_rate = EXCLUDED.multimodal_rate,
    linguistic_count = EXCLUDED.linguistic_count,
    multimodal_count = EXCLUDED.multimodal_count,
    total_votes = EXCLUDED.total_votes,
    total_users = EXCLUDED.total_users,
    index_question_count = EXCLUDED.index_question_count,
    candidate_question_count = EXCLUDED.candidate_question_count,
    updated_at = EXCLUDED.updated_at;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER trigger_sync_daily_metrics
  AFTER INSERT OR UPDATE ON agi_stats
  FOR EACH ROW
  EXECUTE FUNCTION sync_daily_metrics();

-- ============================================
-- 10. 초기 데이터
-- ============================================
INSERT INTO agi_stats (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
SELECT do_recalculate_agi_stats();
