-- ============================================
-- Question Translations Table
-- ============================================
-- Stores translated versions of questions in multiple languages.
-- Run this after 01_schema.sql
-- ============================================

-- ============================================
-- TABLE: question_translations
-- ============================================

CREATE TABLE IF NOT EXISTS question_translations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
  lang_code VARCHAR(5) NOT NULL,  -- 'en', 'ko', 'ja', 'zh', 'es', 'de', 'fr'
  content TEXT NOT NULL,
  is_verified BOOLEAN DEFAULT FALSE,  -- True if this is the original language
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Each question can only have one translation per language
  UNIQUE(question_id, lang_code)
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_translations_question_id ON question_translations(question_id);
CREATE INDEX IF NOT EXISTS idx_translations_lang_code ON question_translations(lang_code);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

ALTER TABLE question_translations ENABLE ROW LEVEL SECURITY;

-- Everyone can read translations
CREATE POLICY "Translations are viewable by everyone"
  ON question_translations FOR SELECT
  USING (true);

-- Only admins can insert/update/delete translations
CREATE POLICY "Only admins can modify translations"
  ON question_translations FOR ALL
  USING ((SELECT is_admin FROM profiles WHERE id = auth.uid()) = true);

-- Edge functions with service role can also modify (bypasses RLS)
-- Note: Service role key automatically bypasses RLS

-- ============================================
-- USAGE
-- ============================================
-- Get translations for a question:
--   SELECT * FROM question_translations WHERE question_id = 123;
--
-- Get question in specific language:
--   SELECT content FROM question_translations
--   WHERE question_id = 123 AND lang_code = 'ko';
-- ============================================
